###
GET http://localhost:8080/v1/address

###
DELETE  http://localhost:8080/v1/address/643109740e0783ebbc3c86ca

###
POST  http://localhost:8080/v1/address
Content-Type: application/json

{
    "name": "Thành phố Hà Nội"
}

###
PATCH  http://localhost:8080/v1/address/643109740e0783ebbc3c86ca
Content-Type: application/json

{
   "name": "Hà Nội"
}
