POST  http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin"
}

###
POST  http://localhost:8080/v1/auth/register
Content-Type: application/json

{
  "userName":"admin78" ,
  "password":"admin78",
  "address":"std1 new york",
  "email": "admintest@gmail.com",
  "phone": "0909898976"
}

